title: William's homepage
description: Welcome to my awesome site. This site is built with Jekyll and hosted on GitHub Pages.
url: "https://WilliamWicaksono1205.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal

markdown: kramdown
